from __future__ import annotations

from langgraph.graph import END, START, StateGraph

from agentic_rag.analyst import AnalystAgent
from agentic_rag.coordinator import Coordinator
from agentic_rag.evidence import EvidenceAgent
from agentic_rag.state import AgentState
from agentic_rag.validation import AnswerValidator


class DeterministicAgenticRAGWorkflow:
    """
    Deterministic, bounded Agentic RAG workflow.

    The workflow uses explicit rule-based routing:

        retrieve
            ↓
        analyze
            ↓
        validate
          ↙   ↘
       retry  finalize
         ↓
      retrieve

    Unlike a fully agent-driven workflow, routing decisions are never
    delegated to an LLM. They are determined entirely from state.
    """

    def __init__(
        self,
        evidence_agent: EvidenceAgent,
        analyst_agent: AnalystAgent | None = None,
        validator: AnswerValidator | None = None,
        max_steps: int = 8,
        max_retries: int = 1,
    ) -> None:
        if max_steps < 4:
            raise ValueError(
                "max_steps must be at least 4 for retrieve, analyze, "
                "validate, and finalize."
            )

        if max_retries < 0:
            raise ValueError("max_retries cannot be negative.")

        self.evidence_agent = evidence_agent
        self.analyst_agent = analyst_agent or AnalystAgent()
        self.validator = validator or AnswerValidator()

        # Kept for compatibility with the existing workflow architecture.
        self.coordinator = Coordinator(max_steps=max_steps)

        self.max_steps = max_steps
        self.max_retries = max_retries

        graph = StateGraph(AgentState)

        graph.add_node("retrieve", self.retrieve)
        graph.add_node("analyze", self.analyze)
        graph.add_node("validate", self.validate)
        graph.add_node("prepare_retry", self.prepare_retry)
        graph.add_node("finalize", self.finalize)

        graph.add_edge(START, "retrieve")
        graph.add_edge("retrieve", "analyze")
        graph.add_edge("analyze", "validate")

        graph.add_conditional_edges(
            "validate",
            self.route_after_validation,
            {
                "retry": "prepare_retry",
                "finalize": "finalize",
            },
        )

        graph.add_edge("prepare_retry", "retrieve")
        graph.add_edge("finalize", END)

        self.graph = graph.compile()

    def _increment_step(self, state: AgentState) -> int:
        """Increment and enforce the global deterministic step limit."""

        step_count = state.get("step_count", 0) + 1

        if step_count > self.max_steps:
            raise RuntimeError(
                "Global deterministic Agentic RAG step limit exceeded."
            )

        return step_count

    def retrieve(self, state: AgentState) -> AgentState:
        """Retrieve evidence using the configured EvidenceAgent."""

        step_count = self._increment_step(state)

        result = self.evidence_agent.run(state)

        decision_log = list(state.get("decision_log", []))
        decision_log.append(
            {
                "agent": "deterministic_coordinator",
                "decision": "retrieve",
                "step": step_count,
            }
        )

        return {
            **result,
            "step_count": step_count,
            "decision_log": decision_log,
        }

    def analyze(self, state: AgentState) -> AgentState:
        """Analyze the retrieved evidence."""

        step_count = self._increment_step(state)

        result = self.analyst_agent.run(state)

        existing_log = list(state.get("decision_log", []))
        result_log = list(result.get("decision_log", []))

        # Preserve any existing workflow history while also preserving
        # log entries generated by the analyst.
        if result_log[: len(existing_log)] == existing_log:
            decision_log = result_log
        else:
            decision_log = existing_log + result_log

        return {
            **result,
            "step_count": step_count,
            "decision_log": decision_log,
        }

    def validate(self, state: AgentState) -> AgentState:
        """Validate the generated answer against the retrieved evidence."""

        step_count = self._increment_step(state)

        result = self.validator.run(state)

        return {
            **result,
            "step_count": step_count,
        }

    def route_after_validation(self, state: AgentState) -> str:
        """
        Deterministic routing policy.

        Rules:

        1. If validation passed, finalize.
        2. If validation failed and retries remain, retry.
        3. If validation failed and no retries remain, finalize.

        No LLM or probabilistic decision is involved.
        """

        validation_passed = self._validation_passed(state)
        retry_count = state.get("retry_count", 0)

        if validation_passed:
            return "finalize"

        if retry_count < self.max_retries:
            return "retry"

        return "finalize"

    def _validation_passed(self, state: AgentState) -> bool:
        """
        Determine validation status from state.

        Supports the common boolean field `validation_passed`.

        If that field is absent, an empty `validation_errors` list is
        treated as a successful validation.
        """

        if "validation_passed" in state:
            return bool(state["validation_passed"])

        validation_errors = state.get("validation_errors", [])

        return len(validation_errors) == 0

    def prepare_retry(self, state: AgentState) -> AgentState:
        """
        Persist a deterministic retry decision before retrieval.

        Retry count is updated explicitly here rather than inside the
        conditional routing function.
        """

        retry_count = state.get("retry_count", 0)

        if retry_count >= self.max_retries:
            raise RuntimeError(
                "Deterministic retry limit exceeded."
            )

        next_retry_count = retry_count + 1

        decision_log = list(state.get("decision_log", []))
        decision_log.append(
            {
                "agent": "deterministic_coordinator",
                "decision": "retry",
                "reason": "validation_failed_and_retry_available",
                "retry_count": next_retry_count,
                "step": state.get("step_count", 0),
            }
        )

        return {
            "retry_count": next_retry_count,
            "decision_log": decision_log,
        }

    def finalize(self, state: AgentState) -> AgentState:
        """Finalize the workflow and persist the final routing decision."""

        step_count = self._increment_step(state)

        decision_log = list(state.get("decision_log", []))
        decision_log.append(
            {
                "agent": "deterministic_coordinator",
                "decision": "finalize",
                "step": step_count,
            }
        )

        return {
            "route": "finalize",
            "step_count": step_count,
            "decision_log": decision_log,
        }

    def run(self, state: AgentState) -> AgentState:
        """Execute the deterministic bounded workflow."""

        state = dict(state)

        state.setdefault("retry_count", 0)
        state.setdefault("step_count", 0)
        state.setdefault("max_steps", self.max_steps)
        state.setdefault("validation_errors", [])
        state.setdefault("decision_log", [])
        state.setdefault("tool_results", [])

        return self.graph.invoke(state)
